### ISSUE TITLE
路径错误问题，建议修掉

### ISSUE THREAD

**Issue by Jackie-5** [17koa/runkoa#15]
在一些node环境上运行runkoa的时候会找不到一些依赖，因为路径有错误。
错误位置：
![image](https://cloud.githubusercontent.com/assets/11611057/19916275/8bea1e62-a0f3-11e6-8709-c6f866b7dbdf.png)
建议：
![image](https://cloud.githubusercontent.com/assets/11611057/19916304/ce369868-a0f3-11e6-9414-63d7667ac7f5.png)

**Comment by i5ting** [comment]
兄弟，发一个pr过来吧

**Comment by OleksiiZubko** [comment]
the same issue with v1.5.3, 
version 1.5.2 woks fine for me

**Comment by i5ting** [comment]
@OleksiiZubko use v1.5.5 for production

**Comment by OleksiiZubko** [comment]
@i5ting thanks, you about 1.5.4? Because I do not see that release https://github.com/17koa/runkoa/releases . 

And I'm using npm "runkoa": "^1.3.1" . Looks like the latest release was 1.5.3 at that moment. And that release was bad. 

Thanks again. Looks like all okay with 1.5.4 now.

**Comment by i5ting** [comment]
@OleksiiZubko 
- release 1.5.6  if use node v7.x，runkoa is an alias with `node --harmony-async-await`

if you have any question, please add an issue to me, thanks

**Comment by OleksiiZubko** [comment]
All works fine, thanks!
